import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { readFile } from 'fs/promises';
import { createHash } from 'crypto';
import { ScreeningLLMService } from './screening-llm.service';
import { foldText, symptomPolarity } from '../../pre-exam-v2/normalization/clinical-text';
import { ScreeningFact } from '../../pre-exam-v2/normalization/screening-input';

export interface EvidenceChunk {
  id: string;
  title: string;
  section: string;
  sourceUrl: string;
  version: string;
  text: string;
  regionIds: string[];
  specialtyCodes: string[];
  minAge: number;
  maxAge: number;
  reviewStatus: 'DRAFT' | 'APPROVED';
  reviewedBy: string | null;
  reviewedAt: string | null;
  expiresAt: string;
  contentHash: string;
  embedding?: number[];
  embeddingModel?: string;
  routingCriteria?: { specialtyCode: string; anySymptoms: string[]; evidenceQuote: string }[];
}
// Criteria must be supplied and clinically reviewed with the source, never generated by the decision LLM.
export function evidenceSupportsFacts(
  chunk: EvidenceChunk,
  facts: ScreeningFact[],
  codes: string[]
): boolean {
  return Boolean(
    chunk.routingCriteria?.some(
      (rule) =>
        codes.includes(rule.specialtyCode) &&
        chunk.text.includes(rule.evidenceQuote) &&
        rule.anySymptoms.some(
          (term) =>
            foldText(rule.evidenceQuote).includes(foldText(term)) &&
            facts.some(
              (f) =>
                f.polarity === 'PRESENT' &&
                f.specialtyCodes.includes(rule.specialtyCode) &&
                symptomPolarity(f.text, [term]) === true
            )
        )
    )
  );
}
export interface EvidenceResult {
  status: 'AVAILABLE' | 'EMPTY' | 'UNAVAILABLE';
  mode: 'HYBRID' | 'LEXICAL' | 'NONE';
  version: string | null;
  chunks: EvidenceChunk[];
}
export function validateEvidenceChunk(chunk: any): chunk is EvidenceChunk {
  return Boolean(
    chunk &&
    ['id', 'title', 'section', 'version', 'text', 'sourceUrl', 'expiresAt', 'contentHash'].every(
      (k) => typeof chunk[k] === 'string' && chunk[k].length > 0
    ) &&
    chunk.text.length <= 8000 &&
    (chunk.routingCriteria === undefined ||
      (Array.isArray(chunk.routingCriteria) &&
        chunk.routingCriteria.every(
          (r: any) =>
            typeof r.specialtyCode === 'string' &&
            chunk.specialtyCodes?.includes(r.specialtyCode) &&
            typeof r.evidenceQuote === 'string' &&
            r.evidenceQuote.length >= 10 &&
            chunk.text.includes(r.evidenceQuote) &&
            Array.isArray(r.anySymptoms) &&
            r.anySymptoms.length > 0 &&
            r.anySymptoms.every(
              (t: any) =>
                typeof t === 'string' &&
                t.length >= 3 &&
                foldText(r.evidenceQuote).includes(foldText(t))
            )
        ))) &&
    /^https:\/\//.test(chunk.sourceUrl) &&
    Number.isFinite(Date.parse(chunk.expiresAt)) &&
    Array.isArray(chunk.regionIds) &&
    chunk.regionIds.every((x: any) => typeof x === 'string') &&
    Array.isArray(chunk.specialtyCodes) &&
    chunk.specialtyCodes.every((x: any) => typeof x === 'string') &&
    Number.isFinite(chunk.minAge) &&
    Number.isFinite(chunk.maxAge) &&
    chunk.minAge <= chunk.maxAge &&
    ['DRAFT', 'APPROVED'].includes(chunk.reviewStatus) &&
    (!chunk.embedding ||
      (typeof chunk.embeddingModel === 'string' &&
        Array.isArray(chunk.embedding) &&
        chunk.embedding.length > 0 &&
        chunk.embedding.every((v: any) => typeof v === 'number' && Number.isFinite(v)))) &&
    (chunk.reviewStatus !== 'APPROVED' ||
      (chunk.reviewedBy?.trim() && Number.isFinite(Date.parse(chunk.reviewedAt)))) &&
    createHash('sha256').update(chunk.text).digest('hex') === chunk.contentHash
  );
}
export function cosine(a: number[], b: number[]): number {
  if (a.length !== b.length || !a.length || [...a, ...b].some((v) => !Number.isFinite(v))) return 0;
  const dot = a.reduce((sum, v, i) => sum + v * b[i], 0);
  const norm = Math.sqrt(a.reduce((s, v) => s + v * v, 0) * b.reduce((s, v) => s + v * v, 0));
  return norm ? dot / norm : 0;
}

@Injectable()
export class ClinicalEvidenceService {
  constructor(
    private config: ConfigService,
    private llm: ScreeningLLMService
  ) {}
  async retrieve(
    query: string,
    regions: string[],
    age: number | null,
    specialtyCodes: string[]
  ): Promise<EvidenceResult> {
    const corpusPath = this.config.get<string>('SCREENING_KNOWLEDGE_PATH');
    if (!corpusPath) return { status: 'EMPTY', mode: 'NONE', version: null, chunks: [] };
    try {
      const corpus = JSON.parse(await readFile(corpusPath, 'utf8'));
      if (
        !Array.isArray(corpus.chunks) ||
        typeof corpus.version !== 'string' ||
        corpus.chunks.some((c: any) => !validateEvidenceChunk(c))
      )
        throw new Error('INVALID_CORPUS');
      if (new Set(corpus.chunks.map((c: EvidenceChunk) => c.id)).size !== corpus.chunks.length)
        throw new Error('DUPLICATE_CHUNK');
      const chunks: EvidenceChunk[] = corpus.chunks.filter(
        (c: EvidenceChunk) =>
          c.reviewStatus === 'APPROVED' &&
          Date.parse(c.expiresAt) > Date.now() &&
          (!c.regionIds.length || c.regionIds.some((r) => regions.includes(r))) &&
          age !== null &&
          age >= c.minAge &&
          age <= c.maxAge &&
          c.specialtyCodes.some((code) => specialtyCodes.includes(code))
      );
      const stopwords = new Set([
        'ban',
        'cua',
        'nguoi',
        'trieu',
        'chung',
        'khong',
        'nhung',
        'nhieu',
        'nao',
        'hay',
        'voi',
        'nhu',
        'khi',
        'sau',
        'truoc',
        'mot',
        'cac',
        'dau',
        'trai',
        'phai',
        'vung',
      ]);
      const terms = [...new Set(foldText(query).match(/[a-z0-9]+/g) || [])].filter(
        (t) => t.length > 2 && !stopwords.has(t)
      );
      const lexical = chunks
        .map((chunk) => {
          const words = new Set(foldText(`${chunk.title} ${chunk.text}`).match(/[a-z0-9]+/g) || []);
          return {
            chunk,
            score: terms.filter((t) => words.has(t)).length / Math.max(terms.length, 1),
          };
        })
        .filter((r) => r.score > 0)
        .sort((a, b) => b.score - a.score);
      let mode: EvidenceResult['mode'] = 'LEXICAL';
      const ranks = new Map<string, number>();
      lexical.slice(0, 20).forEach((r, i) => ranks.set(r.chunk.id, 1 / (60 + i + 1)));
      const vectorChunks = chunks.filter(
        (c) =>
          c.embeddingModel === this.llm.embeddingModel &&
          Array.isArray(c.embedding) &&
          c.embedding.length
      );
      if (vectorChunks.length) {
        try {
          const embedding = await this.llm.embed(query);
          const semantic = vectorChunks
            .map((chunk) => ({ chunk, score: cosine(embedding, chunk.embedding!) }))
            .filter((r) => r.score > 0 && r.chunk.embedding!.length === embedding.length)
            .sort((a, b) => b.score - a.score);
          semantic
            .slice(0, 20)
            .forEach((r, i) =>
              ranks.set(r.chunk.id, (ranks.get(r.chunk.id) || 0) + 1 / (60 + i + 1))
            );
          mode = 'HYBRID';
        } catch {
          /* Explicit lexical retrieval, never substitute a fabricated embedding. */
        }
      }
      const selected = chunks
        .filter((c) => ranks.has(c.id))
        .sort((a, b) => {
          const rank = (c: EvidenceChunk) =>
            ranks.get(c.id)! * (c.regionIds.some((r) => regions.includes(r)) ? 1.1 : 1);
          return rank(b) - rank(a);
        })
        .slice(0, 6);
      return {
        status: selected.length ? 'AVAILABLE' : 'EMPTY',
        mode,
        version: corpus.version,
        chunks: selected,
      };
    } catch {
      return { status: 'UNAVAILABLE', mode: 'NONE', version: null, chunks: [] };
    }
  }
}
