import { Question } from '@/types/screening';

export const QUESTION_BANK: Question[] = [
  // =========================================================================
  // 1. HEAD & FACE REGIONS (head, face) — 10 QUESTIONS PER REGION
  // =========================================================================
  {
    id: 'head_q1',
    category: 'red_flag',
    regionIds: ['head'],
    question: 'Cơn đau đầu có xuất hiện đột ngột, dữ dội chưa từng có trước đây (đau như búa bổ)?',
    subtitle: 'Cảnh báo nguy cơ xuất huyết dưới nhện hoặc tai biến mạch máu não khẩn cấp.',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['neurological', 'pain'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'head_q2',
    category: 'region_specific',
    regionIds: ['head'],
    question: 'Cơn đau đầu bộc phát kèm cảm giác buồn nôn, sợ ánh sáng hoặc sợ tiếng động?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['neurological'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['neurology'] },
  },
  {
    id: 'head_q3',
    category: 'region_specific',
    regionIds: ['head'],
    question: 'Vị trí cơn đau đầu tập trung nhiều nhất ở đâu?',
    type: 'single_choice',
    options: [
      { label: 'Nửa bên đầu (Một bên thái dương)', value: 'one_side', points: 10 },
      { label: 'Vùng sau gáy và cổ', value: 'occipital', points: 12 },
      { label: 'Vùng trán và quanh 2 hốc mắt', value: 'frontal_sinus', points: 8 },
      { label: 'Cảm giác như băng thắt quanh vòm đầu', value: 'tension', points: 5 },
    ],
    priority: 85,
    clinicalTags: ['neurological', 'pain'],
    riskImpact: { suggestSpecialtyIds: ['neurology', 'ent'] },
  },
  {
    id: 'head_q4',
    category: 'region_specific',
    regionIds: ['head'],
    question: 'Bạn có triệu chứng chóng mặt, cảm giác đồ vật xung quanh quay mòng mòng không?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['neurological', 'ent'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['neurology', 'ent'] },
  },
  {
    id: 'head_q5',
    category: 'region_specific',
    regionIds: ['head'],
    question: 'Tình trạng đau đầu diễn ra liên tục hay thành từng cơn bộc phát?',
    type: 'single_choice',
    options: [
      { label: 'Đau râm râm liên tục cả ngày', value: 'constant', points: 8 },
      { label: 'Thành từng cơn giật nhói theo nhịp mạch đập', value: 'pulsatile', points: 12 },
      { label: 'Đau tăng mạnh về sáng sớm khi ngủ dậy', value: 'morning_peak', points: 15 },
    ],
    priority: 75,
    clinicalTags: ['neurological'],
    riskImpact: { suggestSpecialtyIds: ['neurology'] },
  },
  {
    id: 'head_q6',
    category: 'region_specific',
    regionIds: ['head'],
    question: 'Bạn có cảm giác cứng cổ, khó cúi gập cằm chạm ngực không?',
    type: 'boolean',
    priority: 95,
    clinicalTags: ['neurological'],
    riskImpact: { redFlagSeverity: 'HIGH', suggestSpecialtyIds: ['neurology', 'infectious_diseases'] },
  },
  {
    id: 'head_q7',
    category: 'region_specific',
    regionIds: ['head'],
    question: 'Có hiện tượng nhìn mờ, nhìn đôi hoặc thấy chớp sáng trước mắt không?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['neurological', 'ophthalmology'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['neurology', 'ophthalmology'] },
  },
  {
    id: 'head_q8',
    category: 'region_specific',
    regionIds: ['head'],
    question: 'Cơn đau đầu xuất hiện sau khi gặp chấn thương va đập vùng đầu?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['trauma', 'neurological'],
    riskImpact: { redFlagSeverity: 'HIGH', suggestSpecialtyIds: ['neurosurgery', 'traumatology'] },
  },
  {
    id: 'head_q9',
    category: 'region_specific',
    regionIds: ['head'],
    question: 'Cơn đau có tăng lên khi bạn cúi người, ho hoặc hắt hơi không?',
    type: 'boolean',
    priority: 70,
    clinicalTags: ['neurological', 'ent'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['neurology', 'ent'] },
  },
  {
    id: 'head_q10',
    category: 'region_specific',
    regionIds: ['head'],
    question: 'Mức độ ảnh hưởng đến sinh hoạt và công việc hàng ngày của bạn?',
    type: 'single_choice',
    options: [
      { label: 'Nhẹ - Vẫn sinh hoạt bình thường', value: 'mild', points: 5 },
      { label: 'Vừa - Giảm tập trung công việc', value: 'moderate', points: 10 },
      { label: 'Nặng - Phải nằm nghỉ phòng tối, không làm việc được', value: 'severe', points: 20 },
    ],
    priority: 65,
    clinicalTags: ['functional_impairment'],
    riskImpact: { suggestSpecialtyIds: ['neurology'] },
  },

  // FACE REGION (face)
  {
    id: 'face_q1',
    category: 'red_flag',
    regionIds: ['face'],
    question: 'Có dấu hiệu tê méo miệng, sụp mi mắt hoặc không méo lệch mặt đột ngột?',
    subtitle: 'Dấu hiệu liệt dây thần kinh số VII hoặc đột quỵ não.',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['neurological'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'face_q2',
    category: 'region_specific',
    regionIds: ['face'],
    question: 'Cơn đau nhói giật từng cơn như điện giật ở vùng má, quai hàm hay trán?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['neurological', 'pain'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['neurology'] },
  },
  {
    id: 'face_q3',
    category: 'region_specific',
    regionIds: ['face'],
    question: 'Bạn có bị đau tức sưng ấn đau vùng hốc mắt, trán hoặc gò má (nghi xoang)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['ent', 'inflammation'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['ent'] },
  },
  {
    id: 'face_q4',
    category: 'region_specific',
    regionIds: ['face'],
    question: 'Khớp thái dương hàm (quai hàm) có bị đau, kêu rắc rắc khi há miệng hoặc nhai không?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['odonto_stomatology', 'maxillofacial'] },
  },
  {
    id: 'face_q5',
    category: 'region_specific',
    regionIds: ['face'],
    question: 'Có triệu chứng ngạt mũi, chảy mũi nhầy đặc hoặc giảm khứu giác không?',
    type: 'boolean',
    priority: 75,
    clinicalTags: ['ent'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['ent'] },
  },
  {
    id: 'face_q6',
    category: 'region_specific',
    regionIds: ['face'],
    question: 'Vùng da mặt có bị nổi mụn mủ, bọng nước mụn rộp rát đỏ (nghi Zona) không?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['dermatology', 'inflammation'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['dermatology', 'neurology'] },
  },
  {
    id: 'face_q7',
    category: 'region_specific',
    regionIds: ['face'],
    question: 'Đau răng hoặc sưng nướu lợi lan rộng lên vùng mặt?',
    type: 'boolean',
    priority: 70,
    clinicalTags: ['inflammation'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['odonto_stomatology'] },
  },
  {
    id: 'face_q8',
    category: 'region_specific',
    regionIds: ['face'],
    question: 'Mắt có bị đỏ, chảy nước mắt kèm đau nhức sâu trong hốc mắt không?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['ophthalmology'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['ophthalmology'] },
  },
  {
    id: 'face_q9',
    category: 'region_specific',
    regionIds: ['face'],
    question: 'Bạn cảm thấy đau mặt tăng lên khi nhai đồ cứng hay khi nói chuyện?',
    type: 'boolean',
    priority: 65,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['maxillofacial', 'neurology'] },
  },
  {
    id: 'face_q10',
    category: 'region_specific',
    regionIds: ['face'],
    question: 'Thời gian xuất hiện các triệu chứng đau sưng vùng mặt?',
    type: 'single_choice',
    options: [
      { label: 'Mới bị trong vòng 24 - 48 giờ', value: 'acute', points: 10 },
      { label: 'Kéo dài 3 - 7 ngày', value: 'subacute', points: 5 },
      { label: 'Đã kéo dài nhiều tuần / nhiều tháng', value: 'chronic', points: 8 },
    ],
    priority: 60,
    clinicalTags: ['general'],
    riskImpact: { suggestSpecialtyIds: ['ent', 'neurology'] },
  },

  // NECK REGION (neck)
  {
    id: 'neck_q1',
    category: 'red_flag',
    regionIds: ['neck'],
    question: 'Cổ bị cứng nghẹn không thể cúi cằm chạm ngực kèm sốt cao hoặc co giật?',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['neurological', 'inflammation'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'neck_q2',
    category: 'region_specific',
    regionIds: ['neck'],
    question: 'Đau vùng cổ lan xuống vai và tê bì chạy dọc cẳng tay, ngón tay?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['neurological', 'musculoskeletal'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['neurology', 'orthopedics'] },
  },
  {
    id: 'neck_q3',
    category: 'region_specific',
    regionIds: ['neck'],
    question: 'Cổ bị vẹo cứng đau điếng không xoay đầu quay sang hai bên được?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal', 'pain'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics', 'rehabilitation'] },
  },
  {
    id: 'neck_q4',
    category: 'region_specific',
    regionIds: ['neck'],
    question: 'Đau rát gắt vướng họng, khó nuốt thức ăn hoặc nuốt đau?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['ent'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['ent'] },
  },
  {
    id: 'neck_q5',
    category: 'region_specific',
    regionIds: ['neck'],
    question: 'Có nổi hạch sưng đau hoặc sờ thấy khối u cục ở vùng cổ không?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['inflammation'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['ent', 'oncology', 'endocrinology'] },
  },
  {
    id: 'neck_q6',
    category: 'region_specific',
    regionIds: ['neck'],
    question: 'Vùng tuyến giáp trước cổ bị sưng to, cảm giác hồi hộp nghẹn thở hoặc sút cân?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['endocrinology'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['endocrinology'] },
  },
  {
    id: 'neck_q7',
    category: 'region_specific',
    regionIds: ['neck'],
    question: 'Giọng nói có bị khàn đục hoặc mất tiếng kéo dài trên 2 tuần không?',
    type: 'boolean',
    priority: 75,
    clinicalTags: ['ent'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['ent'] },
  },
  {
    id: 'neck_q8',
    category: 'region_specific',
    regionIds: ['neck'],
    question: 'Đau cổ tăng lên khi làm việc máy tính lâu hoặc cúi nhìn điện thoại?',
    type: 'boolean',
    priority: 70,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['orthopedics', 'rehabilitation'] },
  },
  {
    id: 'neck_q9',
    category: 'region_specific',
    regionIds: ['neck'],
    question: 'Tình trạng đau cổ có kèm theo cảm giác mất lực tay, dễ rơi đồ vật không?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['neurological', 'functional_impairment'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['neurosurgery', 'neurology'] },
  },
  {
    id: 'neck_q10',
    category: 'region_specific',
    regionIds: ['neck'],
    question: 'Mức độ đau cổ thắt ngửa khi vận động?',
    type: 'single_choice',
    options: [
      { label: 'Nhe nhẹ mỏi cơ cổ', value: 'mild', points: 5 },
      { label: 'Đau thắt hạn chế quay đầu', value: 'moderate', points: 10 },
      { label: 'Cứng đơ cổ, đau nhói phát khóc khi xoay người', value: 'severe', points: 20 },
    ],
    priority: 65,
    clinicalTags: ['pain'],
    riskImpact: { suggestSpecialtyIds: ['orthopedics'] },
  },

  // =========================================================================
  // 2. SHOULDER & ARM REGIONS (left_shoulder, right_shoulder, left_hand, right_hand...)
  // =========================================================================
  // SHOULDER (left_shoulder, right_shoulder)
  {
    id: 'sh_q1',
    category: 'red_flag',
    regionIds: ['left_shoulder', 'right_shoulder'],
    question: 'Đau vai trái dữ dội lan ra sau lưng hoặc vắt ngang ngực kèm vãi mồ hôi lạnh?',
    subtitle: 'Cảnh báo nhồi máu cơ tim cấp.',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['cardiovascular', 'pain'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'sh_q2',
    category: 'region_specific',
    regionIds: ['left_shoulder', 'right_shoulder'],
    question: 'Bạn có gặp khó khăn khi giơ tay {regionName} cao quá đầu hoặc với tay ra sau lưng?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['musculoskeletal', 'functional_impairment'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['orthopedics', 'rehabilitation'] },
  },
  {
    id: 'sh_q3',
    category: 'region_specific',
    regionIds: ['left_shoulder', 'right_shoulder'],
    question: 'Cơn đau vai tăng mạnh về đêm, đau điếng khi nằm nghiêng đè lên vai {regionName}?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal', 'pain'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'sh_q4',
    category: 'region_specific',
    regionIds: ['left_shoulder', 'right_shoulder'],
    question: 'Khớp vai {regionName} có bị cứng đơ, cảm giác kẹt cứng như bị đông cứng (Frozen Shoulder)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['orthopedics', 'rehabilitation'] },
  },
  {
    id: 'sh_q5',
    category: 'region_specific',
    regionIds: ['left_shoulder', 'right_shoulder'],
    question: 'Có tiếng lạo xạo hoặc khớp vai phát ra tiếng kêu rắc rắc khi xoay cánh tay không?',
    type: 'boolean',
    priority: 75,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'sh_q6',
    category: 'region_specific',
    regionIds: ['left_shoulder', 'right_shoulder'],
    question: 'Khớp vai có bị sưng tấy, đỏ nóng hoặc biến dạng sau té ngã va đập không?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['trauma', 'musculoskeletal'],
    riskImpact: { redFlagSeverity: 'HIGH', suggestSpecialtyIds: ['orthopedics', 'traumatology'] },
  },
  {
    id: 'sh_q7',
    category: 'region_specific',
    regionIds: ['left_shoulder', 'right_shoulder'],
    question: 'Cơ bắp tay hoặc bả vai {regionName} có dấu hiệu teo nhỏ hoặc giảm sức mạnh nhấc vật?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['neurological', 'musculoskeletal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['neurology', 'orthopedics'] },
  },
  {
    id: 'sh_q8',
    category: 'region_specific',
    regionIds: ['left_shoulder', 'right_shoulder'],
    question: 'Đau vai có kèm tê bì lan dọc xuống cẳng tay và các ngón tay không?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['neurological'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['neurology', 'orthopedics'] },
  },
  {
    id: 'sh_q9',
    category: 'region_specific',
    regionIds: ['left_shoulder', 'right_shoulder'],
    question: 'Đau vai {regionName} xuất hiện đột ngột sau khi chơi thể thao (cầu lông, tennis, bơi)?',
    type: 'boolean',
    priority: 70,
    clinicalTags: ['trauma', 'musculoskeletal'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['sports_medicine', 'orthopedics'] },
  },
  {
    id: 'sh_q10',
    category: 'region_specific',
    regionIds: ['left_shoulder', 'right_shoulder'],
    question: 'Thời gian bị đau vai {regionName} kéo dài bao lâu?',
    type: 'single_choice',
    options: [
      { label: 'Dưới 1 tuần', value: 'acute', points: 5 },
      { label: '1 - 4 tuần', value: 'subacute', points: 10 },
      { label: 'Trên 1 tháng', value: 'chronic', points: 15 },
    ],
    priority: 60,
    clinicalTags: ['general'],
    riskImpact: { suggestSpecialtyIds: ['orthopedics'] },
  },

  // HAND & FINGERS (left_hand, right_hand)
  {
    id: 'hd_q1',
    category: 'red_flag',
    regionIds: ['left_hand', 'right_hand'],
    question: 'Bàn tay {regionName} có bị tím tái, mất cảm giác hoàn toàn hoặc không cử động được ngón tay?',
    subtitle: 'Cảnh báo tắc mạch máu hoặc đứt gân/thần kinh cấp tính.',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['neurological', 'trauma'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'hd_q2',
    category: 'region_specific',
    regionIds: ['left_hand', 'right_hand'],
    question: 'Bạn có bị tê bì ngón cái, ngón trỏ và ngón giữa (nghi Hội chứng ống cổ tay)?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['neurological', 'musculoskeletal'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['neurology', 'orthopedics'] },
  },
  {
    id: 'hd_q3',
    category: 'region_specific',
    regionIds: ['left_hand', 'right_hand'],
    question: 'Đau thắt nốt gân cổ tay sát gốc ngón cái khi gập ngón cái (De Quervain)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'hd_q4',
    category: 'region_specific',
    regionIds: ['left_hand', 'right_hand'],
    question: 'Có hiện tượng ngón tay bị kẹt cứng khi gập, phải dùng tay kia kéo bật ra (Ngón tay lò xo)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'hd_q5',
    category: 'region_specific',
    regionIds: ['left_hand', 'right_hand'],
    question: 'Các khớp ngón tay bị sưng đau, cứng khớp vào buổi sáng kéo dài trên 30 phút?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['inflammation', 'musculoskeletal'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['rheumatology'] },
  },
  {
    id: 'hd_q6',
    category: 'region_specific',
    regionIds: ['left_hand', 'right_hand'],
    question: 'Đầu ngón tay bị tái bệch hoặc chuyển màu xanh tím khi tiếp xúc với nước lạnh (Raynaud)?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['neurological', 'cardiovascular'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['rheumatology', 'vascular_surgery'] },
  },
  {
    id: 'hd_q7',
    category: 'region_specific',
    regionIds: ['left_hand', 'right_hand'],
    question: 'Lực cầm nắm của {regionName} bị yếu, thường xuyên làm rơi bát đĩa đồ vật?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['functional_impairment', 'neurological'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['neurology', 'orthopedics'] },
  },
  {
    id: 'hd_q8',
    category: 'region_specific',
    regionIds: ['left_hand', 'right_hand'],
    question: 'Khoé măng ngón tay hoặc bàn tay có ổ sưng tấy mủ nóng đỏ (viêm chín nghé)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['inflammation', 'dermatology'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['general_surgery', 'dermatology'] },
  },
  {
    id: 'hd_q9',
    category: 'region_specific',
    regionIds: ['left_hand', 'right_hand'],
    question: 'Bàn tay hoặc ngón tay bị biến dạng u cục sau chấn thương va đập ngã?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['trauma'],
    riskImpact: { redFlagSeverity: 'HIGH', suggestSpecialtyIds: ['orthopedics', 'traumatology'] },
  },
  {
    id: 'hd_q10',
    category: 'region_specific',
    regionIds: ['left_hand', 'right_hand'],
    question: 'Đau tê bàn tay {regionName} thường bộc phát mạnh nhất vào lúc nào?',
    type: 'single_choice',
    options: [
      { label: 'Nửa đêm rạng sáng làm tỉnh giấc', value: 'night', points: 12 },
      { label: 'Khi làm việc gõ bàn phím / dùng điện thoại', value: 'work', points: 8 },
      { label: 'Liên tục cả ngày không thuyên giảm', value: 'all_day', points: 15 },
    ],
    priority: 70,
    clinicalTags: ['pain'],
    riskImpact: { suggestSpecialtyIds: ['neurology', 'orthopedics'] },
  },

  // ARMS & FOREARMS & ELBOWS (left_upper_arm, right_upper_arm, left_elbow, right_elbow, left_forearm, right_forearm)
  {
    id: 'arm_q1',
    category: 'red_flag',
    regionIds: ['left_upper_arm', 'right_upper_arm', 'left_elbow', 'right_elbow', 'left_forearm', 'right_forearm'],
    question: 'Cánh tay {regionName} bị sưng nề biến dạng, xương đâm lệch hoặc mất hoàn toàn xung mạch đập?',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['trauma'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'arm_q2',
    category: 'region_specific',
    regionIds: ['left_elbow', 'right_elbow'],
    question: 'Đau nhói mặt ngoài khuỷu tay khi vặn nắp chai, vặn khăn hoặc chơi tennis (Tennis Elbow)?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics', 'sports_medicine'] },
  },
  {
    id: 'arm_q3',
    category: 'region_specific',
    regionIds: ['left_elbow', 'right_elbow'],
    question: 'Đau mặt trong khuỷu tay khi gập cổ tay hoặc mang vách đồ vật (Golfer Elbow)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'arm_q4',
    category: 'region_specific',
    regionIds: ['left_upper_arm', 'right_upper_arm', 'left_forearm', 'right_forearm'],
    question: 'Có cảm giác tê bì như kiến bò chạy dọc từ nách xuống cẳng tay?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['neurological'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['neurology'] },
  },
  {
    id: 'arm_q5',
    category: 'region_specific',
    regionIds: ['left_elbow', 'right_elbow'],
    question: 'Khớp khuỷu tay {regionName} có bị kẹt cứng không thể co gập hoặc duỗi thẳng hết mức?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['musculoskeletal', 'functional_impairment'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'arm_q6',
    category: 'region_specific',
    regionIds: ['left_upper_arm', 'right_upper_arm', 'left_forearm', 'right_forearm'],
    question: 'Bắp tay có bị u cục cứng hoặc mảng bầm tím lớn xuất hiện sau va đập không?',
    type: 'boolean',
    priority: 75,
    clinicalTags: ['trauma', 'inflammation'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'arm_q7',
    category: 'region_specific',
    regionIds: ['left_elbow', 'right_elbow'],
    question: 'Tê chèn ép ngón út và ngón áp út khi chống khuỷu tay lên bàn (Hội chứng ống khuỷu)?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['neurological'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['neurology', 'orthopedics'] },
  },
  {
    id: 'arm_q8',
    category: 'region_specific',
    regionIds: ['left_upper_arm', 'right_upper_arm'],
    question: 'Cơ bắp tay bị đau nhói khi co gập cẳng tay chống lại lực cản?',
    type: 'boolean',
    priority: 70,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'arm_q9',
    category: 'region_specific',
    regionIds: ['left_forearm', 'right_forearm'],
    question: 'Cẳng tay bị chuột rút hoặc mỏi nhức cơ liên tục khi gõ bàn phím làm việc?',
    type: 'boolean',
    priority: 65,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 5, suggestSpecialtyIds: ['rehabilitation'] },
  },
  {
    id: 'arm_q10',
    category: 'region_specific',
    regionIds: ['left_upper_arm', 'right_upper_arm', 'left_elbow', 'right_elbow', 'left_forearm', 'right_forearm'],
    question: 'Mức độ ảnh hưởng vận động cánh tay trong sinh hoạt hàng ngày?',
    type: 'single_choice',
    options: [
      { label: 'Nhẹ - Vẫn xách đồ nhẹ được', value: 'mild', points: 5 },
      { label: 'Vừa - Không xách được đồ nặng', value: 'moderate', points: 10 },
      { label: 'Nặng - Không nâng được tay lên', value: 'severe', points: 20 },
    ],
    priority: 60,
    clinicalTags: ['functional_impairment'],
    riskImpact: { suggestSpecialtyIds: ['orthopedics'] },
  },

  // =========================================================================
  // 3. CHEST & ABDOMEN REGIONS (upper_chest, chest, lower_chest, upper_abdomen, abdomen, lower_abdomen)
  // =========================================================================
  // CHEST (upper_chest, chest, lower_chest)
  {
    id: 'ch_q1',
    category: 'red_flag',
    regionIds: ['upper_chest', 'chest', 'lower_chest'],
    question: 'Cơn đau ngực đè nặng, bóp nghẹt sau xương ức lan lên hàm hoặc cánh tay trái?',
    subtitle: 'Cảnh báo hội chứng mạch vành cấp / Nhồi máu cơ tim khẩn cấp.',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['cardiovascular', 'pain'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'ch_q2',
    category: 'region_specific',
    regionIds: ['upper_chest', 'chest', 'lower_chest'],
    question: 'Đau nhói ngực tăng lên rõ rệt khi hít thở sâu, khi ho hoặc khi xoay người?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['respiratory', 'musculoskeletal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['pulmonology', 'cardiology'] },
  },
  {
    id: 'ch_q3',
    category: 'region_specific',
    regionIds: ['upper_chest', 'chest', 'lower_chest'],
    question: 'Cảm giác nóng rát vùng sau xương ức trào ngược lên cổ họng (ợ chua, ợ nóng)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['gastrointestinal'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['gastroenterology'] },
  },
  {
    id: 'ch_q4',
    category: 'region_specific',
    regionIds: ['upper_chest', 'chest', 'lower_chest'],
    question: 'Bạn có cảm giác tim đập nhanh dồn dập, bỏ nhịp hoặc hồi hộp đánh trống ngực?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['cardiovascular'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['cardiology'] },
  },
  {
    id: 'ch_q5',
    category: 'region_specific',
    regionIds: ['upper_chest', 'chest', 'lower_chest'],
    question: 'Có triệu chứng khó thở, thở khò khè hoặc hụt hơi khi leo cầu thang?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['respiratory'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['pulmonology', 'cardiology'] },
  },
  {
    id: 'ch_q6',
    category: 'region_specific',
    regionIds: ['upper_chest', 'chest', 'lower_chest'],
    question: 'Ho kéo dài trên 2 tuần, có ho ra đờm đục hoặc ho ra máu tươi?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['respiratory'],
    riskImpact: { redFlagSeverity: 'HIGH', suggestSpecialtyIds: ['pulmonology'] },
  },
  {
    id: 'ch_q7',
    category: 'region_specific',
    regionIds: ['upper_chest', 'chest', 'lower_chest'],
    question: 'Dùng tay ấn vào các điểm khớp sụn rườn trước ngực có thấy đau nhói tăng lên không?',
    type: 'boolean',
    priority: 75,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['orthopedics', 'internal_medicine'] },
  },
  {
    id: 'ch_q8',
    category: 'region_specific',
    regionIds: ['upper_chest', 'chest', 'lower_chest'],
    question: 'Đau ngực có xuất hiện kèm theo sốt, rét run hoặc vã mồ hôi không?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['inflammation', 'respiratory'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['pulmonology', 'infectious_diseases'] },
  },
  {
    id: 'ch_q9',
    category: 'region_specific',
    regionIds: ['upper_chest', 'chest', 'lower_chest'],
    question: 'Cơn đau ngực kéo dài liên tục bao lâu mỗi lần xuất hiện?',
    type: 'single_choice',
    options: [
      { label: 'Dưới 5 phút (khi gắng sức rồi đỡ)', value: 'angina', points: 15 },
      { label: 'Kéo dài vài giờ râm râm', value: 'hours', points: 8 },
      { label: 'Đau nhói thoáng qua vài giây', value: 'transient', points: 3 },
    ],
    priority: 70,
    clinicalTags: ['cardiovascular'],
    riskImpact: { suggestSpecialtyIds: ['cardiology'] },
  },
  {
    id: 'ch_q10',
    category: 'region_specific',
    regionIds: ['upper_chest', 'chest', 'lower_chest'],
    question: 'Tiền sử gia đình hoặc bản thân có mắc bệnh cao huyết áp, mỡ máu, đái tháo đường?',
    type: 'boolean',
    priority: 65,
    clinicalTags: ['cardiovascular'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['cardiology', 'endocrinology'] },
  },

  // ABDOMEN (upper_abdomen, abdomen, lower_abdomen)
  {
    id: 'ab_q1',
    category: 'red_flag',
    regionIds: ['upper_abdomen', 'abdomen', 'lower_abdomen'],
    question: 'Đau quặn bụng dữ dội kèm nôn ra máu, đi ngoài phân đen như bã cà phê hoặc bụng cứng như gỗ?',
    subtitle: 'Cảnh báo thủng tạng rỗng hoặc xuất huyết tiêu hóa cấp cứu.',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['gastrointestinal', 'pain'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'ab_q2',
    category: 'region_specific',
    regionIds: ['lower_abdomen'],
    question: 'Đau nhói vùng hố chậu phải (bụng dưới bên phải) tăng dần khi di chuyển hoặc ho?',
    subtitle: 'Dấu hiệu cảnh báo viêm ruột thừa cấp.',
    type: 'boolean',
    priority: 95,
    clinicalTags: ['gastrointestinal', 'pain'],
    riskImpact: { redFlagSeverity: 'HIGH', suggestSpecialtyIds: ['gastroenterology', 'general_surgery'] },
  },
  {
    id: 'ab_q3',
    category: 'region_specific',
    regionIds: ['upper_abdomen'],
    question: 'Đau rát vùng thượng vị (trên rốn) bộc phát khi đói hoặc sau khi ăn cay nóng?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['gastrointestinal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['gastroenterology'] },
  },
  {
    id: 'ab_q4',
    category: 'region_specific',
    regionIds: ['upper_abdomen'],
    question: 'Đau quặn hạ sườn phải lan ra sau lưng hoặc vai phải sau bữa ăn nhiều dầu mỡ?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['gastrointestinal'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['gastroenterology', 'hepatobiliary'] },
  },
  {
    id: 'ab_q5',
    category: 'region_specific',
    regionIds: ['upper_abdomen', 'abdomen', 'lower_abdomen'],
    question: 'Có biểu hiện chướng bụng, đầy hơi, buồn nôn hoặc nôn mửa thức ăn?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['gastrointestinal'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['gastroenterology'] },
  },
  {
    id: 'ab_q6',
    category: 'region_specific',
    regionIds: ['upper_abdomen', 'abdomen', 'lower_abdomen'],
    question: 'Thay đổi thói quen đại tiện (tiêu chảy liên tục hoặc táo bón bế tắc, phân nhầy máu)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['gastrointestinal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['gastroenterology'] },
  },
  {
    id: 'ab_q7',
    category: 'region_specific',
    regionIds: ['lower_abdomen'],
    question: 'Đau bụng dưới kèm triệu chứng tiểu buốt, tiểu rắt, tiểu ra máu hoặc tiểu đục?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['gastrointestinal', 'inflammation'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['urology', 'nephrology'] },
  },
  {
    id: 'ab_q8',
    category: 'region_specific',
    regionIds: ['lower_abdomen'],
    question: 'Đối với nữ giới: Đau thắt bụng dưới theo chu kỳ kinh nguyệt hoặc kèm chậm kinh?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['gastrointestinal'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['obstetrics_gynecology'] },
  },
  {
    id: 'ab_q9',
    category: 'region_specific',
    regionIds: ['upper_abdomen', 'abdomen', 'lower_abdomen'],
    question: 'Mắt hoặc da có dấu hiệu vàng ngả màu (nghi bệnh lý gan mật)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['gastrointestinal', 'inflammation'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['gastroenterology', 'hepatology'] },
  },
  {
    id: 'ab_q10',
    category: 'region_specific',
    regionIds: ['upper_abdomen', 'abdomen', 'lower_abdomen'],
    question: 'Bạn có bị sút cân nhanh bất thường (trên 3kg/tháng) không rõ nguyên nhân?',
    type: 'boolean',
    priority: 75,
    clinicalTags: ['general'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['gastroenterology', 'oncology'] },
  },

  // =========================================================================
  // 4. BACK & SPINE REGIONS (upper_back, mid_back, lower_back)
  // =========================================================================
  {
    id: 'bk_q1',
    category: 'red_flag',
    regionIds: ['upper_back', 'mid_back', 'lower_back'],
    question: 'Đau thắt lưng kèm mất kiểm soát đại tiểu tiện (tự chảy) hoặc tê bì toàn bộ vùng bẹn yên ngựa?',
    subtitle: 'Cảnh báo Hội chứng đuôi ngựa (Cauda Equina) cấp cứu thần kinh.',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['neurological', 'pain'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'bk_q2',
    category: 'region_specific',
    regionIds: ['lower_back'],
    question: 'Đau thắt lưng lan xuống mông, chạy dọc đùi và cẳng chân (nghi thần kinh tọa)?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['neurological', 'musculoskeletal'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['neurology', 'orthopedics'] },
  },
  {
    id: 'bk_q3',
    category: 'region_specific',
    regionIds: ['lower_back'],
    question: 'Đau lưng điếng người làm bạn không thể cúi gập lưng hoặc nghiêng người được?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal', 'functional_impairment'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics', 'rehabilitation'] },
  },
  {
    id: 'bk_q4',
    category: 'region_specific',
    regionIds: ['upper_back', 'mid_back'],
    question: 'Đau mỏi nhức vùng bả vai và giữa 2 cột sống lưng khi ngồi làm việc lâu?',
    type: 'boolean',
    priority: 75,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['orthopedics', 'rehabilitation'] },
  },
  {
    id: 'bk_q5',
    category: 'region_specific',
    regionIds: ['lower_back'],
    question: 'Đau thắt lưng bộc phát sau khi bê vắt vật nặng hoặc vận động sai tư thế?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal', 'trauma'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'bk_q6',
    category: 'region_specific',
    regionIds: ['lower_back', 'mid_back'],
    question: 'Cơn đau lưng dữ dội từng quặn bóp lan từ hông ra trước bẹn (nghi sỏi thận)?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['pain'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['urology', 'nephrology'] },
  },
  {
    id: 'bk_q7',
    category: 'region_specific',
    regionIds: ['upper_back', 'mid_back', 'lower_back'],
    question: 'Có hiện tượng cứng cột sống lưng vào buổi sáng, phải đi lại vặn người 30 phút mới đỡ?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['inflammation', 'musculoskeletal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['rheumatology'] },
  },
  {
    id: 'bk_q8',
    category: 'region_specific',
    regionIds: ['lower_back'],
    question: 'Đi bộ một đoạn ngắn (vài trăm mét) phải dừng lại nghỉ vì chân bị tê yếu (cách hồi thần kinh)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['neurological', 'functional_impairment'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['neurosurgery', 'orthopedics'] },
  },
  {
    id: 'bk_q9',
    category: 'region_specific',
    regionIds: ['upper_back', 'mid_back', 'lower_back'],
    question: 'Đau lưng xuất hiện sau tai nạn ngã té nảy mông xuống đất (nghi lún đốt sống)?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['trauma'],
    riskImpact: { redFlagSeverity: 'HIGH', suggestSpecialtyIds: ['orthopedics', 'traumatology'] },
  },
  {
    id: 'bk_q10',
    category: 'region_specific',
    regionIds: ['upper_back', 'mid_back', 'lower_back'],
    question: 'Thời gian bị đau lưng của bạn?',
    type: 'single_choice',
    options: [
      { label: 'Cấp tính (Dưới 2 tuần)', value: 'acute', points: 5 },
      { label: 'Bán cấp (2 - 6 tuần)', value: 'subacute', points: 10 },
      { label: 'Mạn tính kéo dài (Trên 3 tháng)', value: 'chronic', points: 15 },
    ],
    priority: 60,
    clinicalTags: ['general'],
    riskImpact: { suggestSpecialtyIds: ['orthopedics'] },
  },

  // =========================================================================
  // 5. LOWER LIMBS REGIONS (hip, thigh, knee, calf, ankle, foot)
  // =========================================================================
  // KNEE (left_knee, right_knee)
  {
    id: 'kn_q1',
    category: 'red_flag',
    regionIds: ['left_knee', 'right_knee'],
    question: 'Khớp gối {regionName} bị sưng to nóng đỏ dữ dội kèm sốt cao không thể đặt chân xuống đất?',
    subtitle: 'Cảnh báo viêm khớp nhiễm khuẩn hoặc Gút cấp.',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['inflammation', 'trauma'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'kn_q2',
    category: 'region_specific',
    regionIds: ['left_knee', 'right_knee'],
    question: 'Bạn bị đau nhức gối {regionName} khi đi cầu thang, leo dốc hoặc khi ngồi xổm đứng dậy?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'kn_q3',
    category: 'region_specific',
    regionIds: ['left_knee', 'right_knee'],
    question: 'Khớp gối {regionName} phát ra tiếng kêu lạo xạo, rên rẩm khi gập duỗi chân?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['orthopedics', 'rheumatology'] },
  },
  {
    id: 'kn_q4',
    category: 'region_specific',
    regionIds: ['left_knee', 'right_knee'],
    question: 'Có hiện tượng kẹt khớp gối (đang đi bị khựng lại không gấp duỗi được chân)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal', 'functional_impairment'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['orthopedics', 'sports_medicine'] },
  },
  {
    id: 'kn_q5',
    category: 'region_specific',
    regionIds: ['left_knee', 'right_knee'],
    question: 'Cảm giác lỏng gối, bước đi thấy chân bị trượt/sụp (nghi đứt dây chằng)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal', 'trauma'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['orthopedics', 'sports_medicine'] },
  },
  {
    id: 'kn_q6',
    category: 'region_specific',
    regionIds: ['left_knee', 'right_knee'],
    question: 'Khớp gối {regionName} có bị phồng sưng tích dịch nhiều sau chấn thương không?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['inflammation', 'trauma'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'kn_q7',
    category: 'region_specific',
    regionIds: ['left_knee', 'right_knee'],
    question: 'Đau gối kèm cứng khớp vào buổi sáng kéo dài bao lâu?',
    type: 'single_choice',
    options: [
      { label: 'Dưới 15 phút (Thoái hóa khớp)', value: 'oa', points: 8 },
      { label: 'Trên 30 phút - 1 giờ (Viêm khớp dạng thấp)', value: 'ra', points: 15 },
      { label: 'Không bị cứng khớp', value: 'none', points: 0 },
    ],
    priority: 75,
    clinicalTags: ['inflammation'],
    riskImpact: { suggestSpecialtyIds: ['rheumatology', 'orthopedics'] },
  },
  {
    id: 'kn_q8',
    category: 'region_specific',
    regionIds: ['left_knee', 'right_knee'],
    question: 'Đau nhói vùng xương bánh chè phía trước gối khi chạy nhảy?',
    type: 'boolean',
    priority: 70,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['sports_medicine', 'orthopedics'] },
  },
  {
    id: 'kn_q9',
    category: 'region_specific',
    regionIds: ['left_knee', 'right_knee'],
    question: 'Có khối nang sưng mềm phía sau kheo chân (bakers cyst) không?',
    type: 'boolean',
    priority: 70,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'kn_q10',
    category: 'region_specific',
    regionIds: ['left_knee', 'right_knee'],
    question: 'Đau gối {regionName} có tăng lên khi thời tiết thay đổi oi bức giông bão không?',
    type: 'boolean',
    priority: 65,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 5, suggestSpecialtyIds: ['rheumatology', 'orthopedics'] },
  },

  // ANKLE & FOOT (left_ankle, right_ankle, left_foot, right_foot)
  {
    id: 'ft_q1',
    category: 'red_flag',
    regionIds: ['left_ankle', 'right_ankle', 'left_foot', 'right_foot'],
    question: 'Ngón chân cái hoặc cổ chân {regionName} sưng nóng đỏ dữ dội bộc phát trong đêm (Gút) hoặc bàn chân bị lở loét hoại tử?',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['inflammation', 'trauma'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'ft_q2',
    category: 'region_specific',
    regionIds: ['left_foot', 'right_foot'],
    question: 'Đau nhói gót chân khi đặt chân xuống đất bước những bước đầu tiên buổi sáng?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics', 'rehabilitation'] },
  },
  {
    id: 'ft_q3',
    category: 'region_specific',
    regionIds: ['left_ankle', 'right_ankle'],
    question: 'Cổ chân {regionName} bị trật lật bầm tím sưng tấy sau khi bước hụt chân/thể thao?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['trauma', 'musculoskeletal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics', 'traumatology'] },
  },
  {
    id: 'ft_q4',
    category: 'region_specific',
    regionIds: ['left_ankle', 'right_ankle'],
    question: 'Đau thắt gân gót Achill phía sau cổ chân khi kiễng chân cao?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['orthopedics', 'sports_medicine'] },
  },
  {
    id: 'ft_q5',
    category: 'region_specific',
    regionIds: ['left_foot', 'right_foot'],
    question: 'Cảm giác tê bì, rát buốt lòng bàn chân như kiến bò hay kim chích (bệnh thần kinh đái tháo đường)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['neurological', 'endocrinology'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['endocrinology', 'neurology'] },
  },
  {
    id: 'ft_q6',
    category: 'region_specific',
    regionIds: ['left_ankle', 'right_ankle', 'left_foot', 'right_foot'],
    question: 'Cả hai cổ chân có bị sưng phù giữ nước về chiều muộn không?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['cardiovascular', 'inflammation'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['cardiology', 'nephrology'] },
  },
  {
    id: 'ft_q7',
    category: 'region_specific',
    regionIds: ['left_foot', 'right_foot'],
    question: 'Khớp ngón chân cái bị vặn lệch vẹo ra ngoài (Hội chứng Hallux Valgus)?',
    type: 'boolean',
    priority: 70,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'ft_q8',
    category: 'region_specific',
    regionIds: ['left_foot', 'right_foot'],
    question: 'Mặt dưới bàn chân có mụn chai mắt cá đau thấu xương khi dẫm lên?',
    type: 'boolean',
    priority: 70,
    clinicalTags: ['dermatology'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['dermatology', 'orthopedics'] },
  },
  {
    id: 'ft_q9',
    category: 'region_specific',
    regionIds: ['left_ankle', 'right_ankle'],
    question: 'Khớp mắt cá chân bị lỏng lẻo dễ bị lật ngã lặp đi lặp lại?',
    type: 'boolean',
    priority: 75,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'ft_q10',
    category: 'region_specific',
    regionIds: ['left_foot', 'right_foot'],
    question: 'Cơn đau bàn chân {regionName} ảnh hưởng thế nào đến việc đi lại?',
    type: 'single_choice',
    options: [
      { label: 'Đi lại bình thường nhưng mỏi', value: 'mild', points: 5 },
      { label: 'Đi điễng khập khiễng', value: 'moderate', points: 10 },
      { label: 'Không thể chống chân xuống đất', value: 'severe', points: 20 },
    ],
    priority: 60,
    clinicalTags: ['functional_impairment'],
    riskImpact: { suggestSpecialtyIds: ['orthopedics'] },
  },

  // HIPS & THIGHS & CALVES (left_hip, right_hip, left_thigh, right_thigh, left_calf, right_calf)
  {
    id: 'hp_q1',
    category: 'red_flag',
    regionIds: ['left_hip', 'right_hip', 'left_thigh', 'right_thigh', 'left_calf', 'right_calf'],
    question: 'Bắp chân {regionName} bị sưng to nóng đỏ căng cứng một bên đột ngột (nghi huyết khối tĩnh mạch sâu)?',
    type: 'boolean',
    priority: 100,
    clinicalTags: ['cardiovascular', 'inflammation'],
    riskImpact: { redFlagSeverity: 'CRITICAL' },
  },
  {
    id: 'hp_q2',
    category: 'region_specific',
    regionIds: ['left_hip', 'right_hip'],
    question: 'Đau nhức khớp háng {regionName} khi bước đi, đi khập khiễng hoặc khó xoay vặn chân?',
    type: 'boolean',
    priority: 90,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'hp_q3',
    category: 'region_specific',
    regionIds: ['left_hip', 'right_hip'],
    question: 'Cứng khớp háng khó co chân lên mặc quần hoặc cắt móng chân buổi sáng?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal', 'functional_impairment'],
    riskImpact: { addPoints: 12, suggestSpecialtyIds: ['orthopedics', 'rheumatology'] },
  },
  {
    id: 'hp_q4',
    category: 'region_specific',
    regionIds: ['left_calf', 'right_calf'],
    question: 'Bắp chân {regionName} hay bị chuột rút co thắt gây đau điếng vào ban đêm?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['neurology', 'vascular_surgery'] },
  },
  {
    id: 'hp_q5',
    category: 'region_specific',
    regionIds: ['left_calf', 'right_calf'],
    question: 'Nhìn thấy các búi tĩnh mạch ngoằn ngoèo nổi rõ dưới da bắp chân (giãn tĩnh mạch)?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['cardiovascular'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['vascular_surgery'] },
  },
  {
    id: 'hp_q6',
    category: 'region_specific',
    regionIds: ['left_thigh', 'right_thigh'],
    question: 'Đau rát buốt da mặt ngoài đùi khi sờ chạm vào (mặt ngoài đùi)?',
    type: 'boolean',
    priority: 75,
    clinicalTags: ['neurological'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['neurology'] },
  },
  {
    id: 'hp_q7',
    category: 'region_specific',
    regionIds: ['left_hip', 'right_hip'],
    question: 'Đau nhói hông {regionName} lan xuống mông đùi sau khi ngồi trên ghế cứng quá lâu?',
    type: 'boolean',
    priority: 75,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 8, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'hp_q8',
    category: 'region_specific',
    regionIds: ['left_thigh', 'right_thigh'],
    question: 'Cơ đùi bị đau rách nhói sau khi bứt tốc chạy nhảy thể thao?',
    type: 'boolean',
    priority: 80,
    clinicalTags: ['trauma', 'musculoskeletal'],
    riskImpact: { addPoints: 10, suggestSpecialtyIds: ['sports_medicine', 'orthopedics'] },
  },
  {
    id: 'hp_q9',
    category: 'region_specific',
    regionIds: ['left_hip', 'right_hip'],
    question: 'Tiền sử có uống rượu bia nhiều hoặc sử dụng thuốc Corticoid kéo dài (nghi hoại tử chỏm xương đùi)?',
    type: 'boolean',
    priority: 85,
    clinicalTags: ['musculoskeletal'],
    riskImpact: { addPoints: 15, suggestSpecialtyIds: ['orthopedics'] },
  },
  {
    id: 'hp_q10',
    category: 'region_specific',
    regionIds: ['left_thigh', 'right_thigh', 'left_calf', 'right_calf'],
    question: 'Cảm giác mỏi chân nặng chân xuất hiện rõ nhất lúc nào?',
    type: 'single_choice',
    options: [
      { label: 'Cuối ngày sau khi đứng lâu', value: 'evening', points: 8 },
      { label: 'Sau khi đi bộ vài trăm mét', value: 'walking', points: 12 },
      { label: 'Nằm nghỉ ngơi cũng đau mỏi', value: 'rest', points: 15 },
    ],
    priority: 65,
    clinicalTags: ['general'],
    riskImpact: { suggestSpecialtyIds: ['vascular_surgery', 'orthopedics'] },
  },
];
